#!/usr/bin/env python3
"""Seed the magic-ok approval registry from residual bypasses.

Run ONCE after Phase 2 refactoring, before activating the hook in
.claude/settings.json. Walks the repo for every '# magic-ok: <reason>'
comment, pairs it with the literal on that line, and writes a DRAFT
registry file to .claude/magic-ok-approvals.draft.yaml.

The user reviews the draft, deletes entries they want refactored out
(bypass refused -> literal must move to config), then renames the file
to .claude/magic-ok-approvals.yaml to make the approvals live.

CLI:
    python3 bootstrap_baseline.py              # writes the draft + prints summary
    python3 bootstrap_baseline.py --print      # prints only (no file write)

Excludes: .git, .venv, venv, node_modules, __pycache__, workspace, memory,
scripts/hooks (policy-exempt).
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import re
import sys
from pathlib import Path

_HOOKS_DIR = Path(__file__).resolve().parent
if str(_HOOKS_DIR) not in sys.path:
    sys.path.insert(0, str(_HOOKS_DIR))

import check_magic_constants as detector  # noqa: E402

REPO_ROOT = _HOOKS_DIR.parent.parent
DRAFT_PATH = REPO_ROOT / ".claude" / "magic-ok-approvals.draft.yaml"
LIVE_PATH = REPO_ROOT / ".claude" / "magic-ok-approvals.yaml"
EXCLUDE_PARTS = {".git", ".venv", "venv", "node_modules",
                 "__pycache__", "workspace", "memory"}
POLICY_EXEMPT_RELATIVE = Path("scripts") / "hooks"
MAGIC_OK_RE = re.compile(r"#\s*magic-ok:\s*(\S.*?)\s*$")


def _iter_py_files():
    for p in REPO_ROOT.rglob("*.py"):
        rel = p.relative_to(REPO_ROOT)
        parts = set(rel.parts)
        if parts & EXCLUDE_PARTS:
            continue
        # Policy carve-out: scripts/hooks/*.py
        try:
            rel.relative_to(POLICY_EXEMPT_RELATIVE)
            continue
        except ValueError:
            pass
        yield p


def _fingerprint(rel_path, literal_repr, reason):
    raw = f"{rel_path}|{literal_repr}|{reason}".encode("utf-8")
    return hashlib.sha256(raw).hexdigest()


def _extract_bypasses(file_path):
    try:
        text = file_path.read_text(encoding="utf-8")
    except OSError:
        return []
    try:
        tree = ast.parse(text, filename=str(file_path))
    except SyntaxError:
        return []

    doc_ids = detector.collect_docstring_node_ids(tree)
    constants_by_line = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.Constant):
            continue
        if id(node) in doc_ids:
            continue
        if node.value is Ellipsis:
            continue
        if detector.is_exempt(node.value):
            continue
        line = getattr(node, "lineno", 0) or 0
        if line and line not in constants_by_line:
            constants_by_line[line] = node

    rel = str(file_path.relative_to(REPO_ROOT))
    out = []
    for idx, line in enumerate(text.splitlines(), start=1):
        m = MAGIC_OK_RE.search(line)
        if not m:
            continue
        reason = m.group(1).strip()
        if not reason:
            continue
        node = constants_by_line.get(idx)
        if node is None:
            continue
        literal_repr = detector._truncate(node.value)
        out.append({
            "path": rel,
            "line": idx,
            "literal_repr": literal_repr,
            "reason": reason,
            "fingerprint": _fingerprint(rel, literal_repr, reason),
        })
    return out


def _format_draft(all_bypasses):
    lines = [
        "# Magic-OK approval registry (DRAFT)",
        "#",
        "# Generated by scripts/hooks/bootstrap_baseline.py on first activation.",
        "# Review each entry. Delete entries you want refactored out of code",
        "# (the literal must move to config/ instead). Keep entries you want",
        "# to remain as bypassed literals.",
        "#",
        "# When satisfied, rename this file to magic-ok-approvals.yaml to",
        "# activate the approvals live.",
        "",
        "approvals:",
    ]
    if not all_bypasses:
        lines.append("  []")
        return "\n".join(lines) + "\n"
    for b in all_bypasses:
        lines.extend([
            f"  - fingerprint: \"{b['fingerprint']}\"",
            f"    path: \"{b['path']}\"",
            f"    line: {b['line']}",
            f"    literal: {b['literal_repr']}",
            f"    reason: \"{b['reason']}\"",
        ])
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(
        description="Seed magic-ok registry from residual bypasses.")
    parser.add_argument("--print", action="store_true", dest="print_only",
                        help="Print to stdout; do not write draft file")
    args = parser.parse_args()

    all_bypasses = []
    files_scanned = 0
    for p in _iter_py_files():
        files_scanned += 1
        all_bypasses.extend(_extract_bypasses(p))

    draft = _format_draft(all_bypasses)

    if args.print_only:
        sys.stdout.write(draft)
        print(
            f"\n# --- scanned {files_scanned} files, "
            f"found {len(all_bypasses)} bypasses ---",
            file=sys.stderr,
        )
        return

    if LIVE_PATH.exists():
        print(
            f"NOTE: live registry already exists at {LIVE_PATH}. "
            f"Draft will still be written to {DRAFT_PATH} for comparison.",
            file=sys.stderr,
        )

    DRAFT_PATH.parent.mkdir(parents=True, exist_ok=True)
    DRAFT_PATH.write_text(draft, encoding="utf-8")
    print(f"Wrote draft registry: {DRAFT_PATH}")
    print(f"  files scanned : {files_scanned}")
    print(f"  bypasses found: {len(all_bypasses)}")
    print("")
    print("Next steps:")
    print(f"  1. Review {DRAFT_PATH} and delete entries you want refactored.")
    print("  2. Rename to magic-ok-approvals.yaml to make it live:")
    print(f"     mv {DRAFT_PATH} {LIVE_PATH}")
    print("  3. Then register hooks in .claude/settings.json.")


if __name__ == "__main__":
    main()
